baseurl = "https://jimmyislive.dev"
languageCode = "en"
title = "@jimmyislive"
theme = "tale-hugo"
disqusShortname = ""
googleAnalytics = ""
enableEmoji = true
enableRobotsTXT = true
preserveTaxonomyNames = true

[params]
author.name = "Jimmy John"
hideDarkModeToggle = true

[taxonomies]
tag = "tags"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true  





