baseurl = "https://jimmyislive.dev"
languageCode = "en"
title = "@jimmyislive"
theme = "tale-hugo"
disqusShortname = ""
googleAnalytics = ""
enableEmoji = true
enableRobotsTXT = true
preserveTaxonomyNames = true

[params]
author = "Jimmy John"

[taxonomies]
  tag = "tags"

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true  

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.122.0"

